version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_tracking
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data